version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pihole.rule=Host(`pihole`)"
      - "traefik.http.routers.pihole.entrypoints=http"
    image: pihole/pihole:latest
    hostname: 'pihole'
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "8000:8000/tcp"
      - "4430:4430/tcp"
    environment:
      TZ: 'Europe/Berlin'
      WEBPASSWORD: 'admin'
      FTLCONF_REPLY_ADDR4: '192.168.178.100'
    dns:
      - 127.0.0.1
      - 8.8.8.8
    volumes:
      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
