version: "3.3"
services:

  traefik:
    image: "traefik:v2.7"
    container_name: "traefik"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./log/traefik:/log/traefik"
      - "./traefik_data/traefik.yml:/traefik.yml"
      - "./traefik_data/dynamic.yml:/dynamic.yml"
      - "/etc/localtime:/etc/localtime:ro"

  whoami:
    image: "containous/whoami"
    container_name: "whoami"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.$DOMAIN`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls.certresolver=myresolver"

  pihole:
    image: "pihole/pihole:latest"
    container_name: "pihole"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pihole.rule=Host(`$DOMAIN`, `pihole.$DOMAIN`)"
      - "traefik.http.routers.pihole.entrypoints=websecure"
      - "traefik.http.routers.pihole.tls.certresolver=myresolver"
    hostname: 'pihole'
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "8000:8000/tcp"
      - "4430:4430/tcp"
    environment:
      TZ: 'Europe/Berlin'
      WEBPASSWORD: 'admin'
      FTLCONF_REPLY_ADDR4: '192.168.178.100'
    dns:
      - 127.0.0.1
      - 8.8.8.8
    volumes:
      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    networks:
      - default
      - web

networks:
  web:
    external: true
