---
- name: Create traefik folder on Pi.
  ansible.builtin.file:
    path: "{{ config_dir }}/traefik"
    state: directory
    mode: 0755
  become: false

- name: Copy traefik docker-compose template to Pi.
  ansible.builtin.template:
    src: templates/{{ item.src }}
    dest: "{{ config_dir }}/traefik/{{ item.dest }}"
    mode: '0640'
  loop:
    - src: traefik-docker-compose.yml.j2
      dest: docker-compose.yml
    - src: .env
      dest: .env
  become: false
  # notify: Restart traefik

# TODO: The first time this playbook is run, the `pi` user may not be added
# to the `docker` group, so this task may fail.
- name: Ensure traefik is running.
  community.docker.docker_compose:
    project_src: "{{ config_dir }}/traefik/"
    build: false
  become: false
