---
- name: Create traefik folder on Pi.
  ansible.builtin.file:
    path: "{{ config_dir }}/traefik"
    state: directory
    mode: 0755
  become: false

- name: Create letsencrypt folder on Pi.
  ansible.builtin.file:
    path: "{{ config_dir }}/traefik/letsencrypt"
    state: directory
    mode: "0755"
  become: false

- name: Create configuration folder on Pi.
  ansible.builtin.file:
    path: "{{ config_dir }}/traefik/configuration"
    state: directory
    mode: "0755"
  become: false

- name: Copy traefik configuration to Pi.
  ansible.builtin.template:
    src: templates/{{ item.src }}
    dest: "{{ config_dir }}/traefik/configuration/{{ item.dest }}"
    mode: "0644"
    owner: pi
    group: pi
  loop:
    - src: traefik-dynamic.yml.j2
      dest: dynamic.yml
    - src: traefik.yml.j2
      dest: traefik.yml
  become: false

- name: Copy traefik .env file to Pi.
  ansible.builtin.copy:
    src: .env
    dest: "{{ config_dir }}/traefik/.env"
    mode: "0755"
  become: false

- name: Create ACME file for traefik
  ansible.builtin.file:
    path: "{{ config_dir }}/traefik/letsencrypt/acme.json"
    state: touch
    mode: "0600"
  become: false

- name: Copy traefik docker-compose template to Pi.
  ansible.builtin.template:
    src: templates/traefik-docker-compose.yml.j2
    dest: "{{ config_dir }}/traefik/docker-compose.yml"
    mode: "0640"
  become: false
  notify: Restart traefik

# TODO: The first time this playbook is run, the `pi` user may not be added
# to the `docker` group, so this task may fail.
- name: Ensure traefik is running.
  community.docker.docker_compose:
    project_src: "{{ config_dir }}/traefik/"
    build: false
  become: false
